# Generated by Django 5.2.18 on 2026-10-10 12:43

from django.db import migrations

import forklift_web.core.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="spec",
            field=forklift_web.core.models.fields.OrderedJSONField(),
        ),
        migrations.AlterField(
            model_name="schemaversion",
            name="document",
            field=forklift_web.core.models.fields.OrderedJSONField(),
        ),
    ]
