"""Print a .env file with fresh random secrets for the Compose stack.

    python deploy/compose/generate_env.py > deploy/compose/.env

Standard library only. Keep the file private: it holds the admin password, the database
password, the store's root credentials and the keys that encrypt connection secrets.
"""

import base64
import secrets


def token(nbytes: int = 24) -> str:
    return secrets.token_urlsafe(nbytes)


# Fernet keys are 32 random bytes, url-safe base64
fernet_key = base64.urlsafe_b64encode(secrets.token_bytes(32)).decode()

print(f"""# Generated by generate_env.py: random secrets for one installation; keep it private.
FORKLIFT_SECRET_KEY={token(48)}
FORKLIFT_SECRETS_KEYS={fernet_key}
FORKLIFT_DB_PASSWORD={token()}
FORKLIFT_STORE_ACCESS_KEY=forklift-{secrets.token_hex(6)}
FORKLIFT_STORE_SECRET_KEY={token(32)}
FORKLIFT_ADMIN_USERNAME=admin
FORKLIFT_ADMIN_PASSWORD={token(18)}

# Where people reach the UI and the store (change both when the stack is not on localhost)
FORKLIFT_PUBLIC_URL=http://localhost:8080
FORKLIFT_PUBLIC_STORE_URL=http://localhost:9000
FORKLIFT_ALLOWED_HOSTS=localhost,127.0.0.1,gateway""")
